hoistPattern:
  - '*'
hoistedDependencies:
  '@babel/code-frame@7.27.1':
    '@babel/code-frame': private
  '@babel/helper-validator-identifier@7.27.1':
    '@babel/helper-validator-identifier': private
  '@pm2/agent@2.1.1':
    '@pm2/agent': private
  '@pm2/blessed@0.1.81':
    '@pm2/blessed': private
  '@pm2/io@6.1.0':
    '@pm2/io': private
  '@pm2/js-api@0.8.0':
    '@pm2/js-api': private
  '@pm2/pm2-version-check@1.0.4':
    '@pm2/pm2-version-check': private
  '@puppeteer/browsers@1.9.1':
    '@puppeteer/browsers': private
  '@tootallnate/quickjs-emscripten@0.23.0':
    '@tootallnate/quickjs-emscripten': private
  '@types/node-fetch@2.6.13':
    '@types/node-fetch': private
  '@types/node@24.9.0':
    '@types/node': private
  '@types/yauzl@2.10.3':
    '@types/yauzl': private
  accepts@1.3.8:
    accepts: private
  agent-base@7.1.4:
    agent-base: private
  ajv@6.12.6:
    ajv: private
  amp-message@0.1.2:
    amp-message: private
  amp@0.3.1:
    amp: private
  ansi-colors@4.1.3:
    ansi-colors: private
  ansi-regex@5.0.1:
    ansi-regex: private
  ansi-styles@4.3.0:
    ansi-styles: private
  ansis@4.0.0-node10:
    ansis: private
  anymatch@3.1.3:
    anymatch: private
  argparse@2.0.1:
    argparse: private
  array-flatten@1.1.1:
    array-flatten: private
  arrify@2.0.1:
    arrify: private
  ast-types@0.13.4:
    ast-types: private
  async@3.2.6:
    async: private
  asynckit@0.4.0:
    asynckit: private
  b4a@1.7.3:
    b4a: private
  bare-events@2.8.0:
    bare-events: private
  base64-js@1.5.1:
    base64-js: private
  basic-ftp@5.0.5:
    basic-ftp: private
  bignumber.js@9.3.1:
    bignumber.js: private
  binary-extensions@2.3.0:
    binary-extensions: private
  bodec@0.1.0:
    bodec: private
  body-parser@1.20.3:
    body-parser: private
  braces@3.0.3:
    braces: private
  buffer-crc32@0.2.13:
    buffer-crc32: private
  buffer-equal-constant-time@1.0.1:
    buffer-equal-constant-time: private
  buffer-from@1.1.2:
    buffer-from: private
  buffer@5.7.1:
    buffer: private
  bytes@3.1.2:
    bytes: private
  call-bind-apply-helpers@1.0.2:
    call-bind-apply-helpers: private
  call-bound@1.0.4:
    call-bound: private
  callsites@3.1.0:
    callsites: private
  chalk@3.0.0:
    chalk: private
  charm@0.1.2:
    charm: private
  chokidar@3.6.0:
    chokidar: private
  chromium-bidi@0.5.8(devtools-protocol@0.0.1232444):
    chromium-bidi: private
  cli-tableau@2.0.1:
    cli-tableau: private
  cliui@8.0.1:
    cliui: private
  color-convert@2.0.1:
    color-convert: private
  color-name@1.1.4:
    color-name: private
  combined-stream@1.0.8:
    combined-stream: private
  commander@2.15.1:
    commander: private
  content-disposition@0.5.4:
    content-disposition: private
  content-type@1.0.5:
    content-type: private
  cookie-signature@1.0.6:
    cookie-signature: private
  cookie@0.7.1:
    cookie: private
  cors@2.8.5:
    cors: private
  cosmiconfig@9.0.0:
    cosmiconfig: private
  croner@4.1.97:
    croner: private
  cross-fetch@4.0.0:
    cross-fetch: private
  cross-spawn@7.0.6:
    cross-spawn: private
  culvert@0.1.2:
    culvert: private
  data-uri-to-buffer@6.0.2:
    data-uri-to-buffer: private
  dayjs@1.11.15:
    dayjs: private
  debug@2.6.9:
    debug: private
  degenerator@5.0.1:
    degenerator: private
  delayed-stream@1.0.0:
    delayed-stream: private
  depd@2.0.0:
    depd: private
  destroy@1.2.0:
    destroy: private
  devtools-protocol@0.0.1232444:
    devtools-protocol: private
  dunder-proto@1.0.1:
    dunder-proto: private
  ecdsa-sig-formatter@1.0.11:
    ecdsa-sig-formatter: private
  ee-first@1.1.1:
    ee-first: private
  emoji-regex@8.0.0:
    emoji-regex: private
  encodeurl@2.0.0:
    encodeurl: private
  end-of-stream@1.4.5:
    end-of-stream: private
  enquirer@2.3.6:
    enquirer: private
  env-paths@2.2.1:
    env-paths: private
  error-ex@1.3.4:
    error-ex: private
  es-define-property@1.0.1:
    es-define-property: private
  es-errors@1.3.0:
    es-errors: private
  es-object-atoms@1.1.1:
    es-object-atoms: private
  es-set-tostringtag@2.1.0:
    es-set-tostringtag: private
  escalade@3.2.0:
    escalade: private
  escape-html@1.0.3:
    escape-html: private
  escape-string-regexp@4.0.0:
    escape-string-regexp: private
  escodegen@2.1.0:
    escodegen: private
  esprima@4.0.1:
    esprima: private
  estraverse@5.3.0:
    estraverse: private
  esutils@2.0.3:
    esutils: private
  etag@1.8.1:
    etag: private
  eventemitter2@5.0.1:
    eventemitter2: private
  events-universal@1.0.1:
    events-universal: private
  eventsource-parser@3.0.6:
    eventsource-parser: private
  eventsource@3.0.7:
    eventsource: private
  express-rate-limit@7.5.1(express@5.1.0):
    express-rate-limit: private
  extend@3.0.2:
    extend: private
  extract-zip@2.0.1:
    extract-zip: private
  extrareqp2@1.0.0(debug@4.3.4):
    extrareqp2: private
  fast-deep-equal@3.1.3:
    fast-deep-equal: private
  fast-fifo@1.3.2:
    fast-fifo: private
  fast-json-patch@3.1.1:
    fast-json-patch: private
  fast-json-stable-stringify@2.1.0:
    fast-json-stable-stringify: private
  fast-text-encoding@1.0.6:
    fast-text-encoding: private
  fclone@1.0.11:
    fclone: private
  fd-slicer@1.1.0:
    fd-slicer: private
  fill-range@7.1.1:
    fill-range: private
  finalhandler@1.3.1:
    finalhandler: private
  follow-redirects@1.15.11(debug@4.3.4):
    follow-redirects: private
  form-data@4.0.4:
    form-data: private
  forwarded@0.2.0:
    forwarded: private
  fresh@0.5.2:
    fresh: private
  fsevents@2.3.3:
    fsevents: private
  function-bind@1.1.2:
    function-bind: private
  gaxios@5.1.3:
    gaxios: private
  gcp-metadata@5.3.0:
    gcp-metadata: private
  get-caller-file@2.0.5:
    get-caller-file: private
  get-intrinsic@1.3.0:
    get-intrinsic: private
  get-proto@1.0.1:
    get-proto: private
  get-stream@5.2.0:
    get-stream: private
  get-uri@6.0.5:
    get-uri: private
  git-node-fs@1.0.0(js-git@0.7.8):
    git-node-fs: private
  git-sha1@0.1.2:
    git-sha1: private
  glob-parent@5.1.2:
    glob-parent: private
  google-auth-library@8.9.0:
    google-auth-library: private
  google-p12-pem@4.0.1:
    google-p12-pem: private
  googleapis-common@6.0.4:
    googleapis-common: private
  gopd@1.2.0:
    gopd: private
  gtoken@6.1.2:
    gtoken: private
  has-flag@4.0.0:
    has-flag: private
  has-symbols@1.1.0:
    has-symbols: private
  has-tostringtag@1.0.2:
    has-tostringtag: private
  hasown@2.0.2:
    hasown: private
  http-errors@2.0.0:
    http-errors: private
  http-proxy-agent@7.0.2:
    http-proxy-agent: private
  https-proxy-agent@5.0.1:
    https-proxy-agent: private
  iconv-lite@0.4.24:
    iconv-lite: private
  ieee754@1.2.1:
    ieee754: private
  import-fresh@3.3.1:
    import-fresh: private
  inherits@2.0.4:
    inherits: private
  ini@1.3.8:
    ini: private
  ip-address@10.0.1:
    ip-address: private
  ipaddr.js@1.9.1:
    ipaddr.js: private
  is-arrayish@0.2.1:
    is-arrayish: private
  is-binary-path@2.1.0:
    is-binary-path: private
  is-core-module@2.16.1:
    is-core-module: private
  is-extglob@2.1.1:
    is-extglob: private
  is-fullwidth-code-point@3.0.0:
    is-fullwidth-code-point: private
  is-glob@4.0.3:
    is-glob: private
  is-number@7.0.0:
    is-number: private
  is-promise@4.0.0:
    is-promise: private
  is-stream@2.0.1:
    is-stream: private
  isexe@2.0.0:
    isexe: private
  js-git@0.7.8:
    js-git: private
  js-tokens@4.0.0:
    js-tokens: private
  js-yaml@4.1.0:
    js-yaml: private
  json-bigint@1.0.0:
    json-bigint: private
  json-parse-even-better-errors@2.3.1:
    json-parse-even-better-errors: private
  json-schema-traverse@0.4.1:
    json-schema-traverse: private
  json-stringify-safe@5.0.1:
    json-stringify-safe: private
  jwa@2.0.1:
    jwa: private
  jws@4.0.0:
    jws: private
  lines-and-columns@1.2.4:
    lines-and-columns: private
  lodash@4.17.21:
    lodash: private
  lru-cache@6.0.0:
    lru-cache: private
  math-intrinsics@1.1.0:
    math-intrinsics: private
  media-typer@0.3.0:
    media-typer: private
  merge-descriptors@1.0.3:
    merge-descriptors: private
  methods@1.1.2:
    methods: private
  mime-db@1.52.0:
    mime-db: private
  mime-types@2.1.35:
    mime-types: private
  mime@1.6.0:
    mime: private
  mitt@3.0.1:
    mitt: private
  mkdirp-classic@0.5.3:
    mkdirp-classic: private
  mkdirp@1.0.4:
    mkdirp: private
  module-details-from-path@1.0.4:
    module-details-from-path: private
  ms@2.0.0:
    ms: private
  mute-stream@0.0.8:
    mute-stream: private
  needle@2.4.0:
    needle: private
  negotiator@0.6.3:
    negotiator: private
  netmask@2.0.2:
    netmask: private
  node-fetch@2.7.0:
    node-fetch: private
  node-forge@1.3.1:
    node-forge: private
  normalize-path@3.0.0:
    normalize-path: private
  object-assign@4.1.1:
    object-assign: private
  object-inspect@1.13.4:
    object-inspect: private
  on-finished@2.4.1:
    on-finished: private
  once@1.4.0:
    once: private
  pac-proxy-agent@7.2.0:
    pac-proxy-agent: private
  pac-resolver@7.0.1:
    pac-resolver: private
  pako@0.2.9:
    pako: private
  parent-module@1.0.1:
    parent-module: private
  parse-json@5.2.0:
    parse-json: private
  parseurl@1.3.3:
    parseurl: private
  path-key@3.1.1:
    path-key: private
  path-parse@1.0.7:
    path-parse: private
  path-to-regexp@0.1.12:
    path-to-regexp: private
  pend@1.2.0:
    pend: private
  picocolors@1.1.1:
    picocolors: private
  picomatch@2.3.1:
    picomatch: private
  pidusage@3.0.2:
    pidusage: private
  pkce-challenge@5.0.0:
    pkce-challenge: private
  pm2-axon-rpc@0.7.1:
    pm2-axon-rpc: private
  pm2-axon@4.0.1:
    pm2-axon: private
  pm2-deploy@1.0.2:
    pm2-deploy: private
  pm2-multimeter@0.1.2:
    pm2-multimeter: private
  pm2-sysmonit@1.2.8:
    pm2-sysmonit: private
  progress@2.0.3:
    progress: private
  promptly@2.2.0:
    promptly: private
  proxy-addr@2.0.7:
    proxy-addr: private
  proxy-agent@6.3.1:
    proxy-agent: private
  proxy-agent@6.4.0:
    proxy-agent: private
  proxy-from-env@1.1.0:
    proxy-from-env: private
  pump@3.0.3:
    pump: private
  punycode@2.3.1:
    punycode: private
  puppeteer-core@21.11.0:
    puppeteer-core: private
  qs@6.13.0:
    qs: private
  range-parser@1.2.1:
    range-parser: private
  raw-body@3.0.1:
    raw-body: private
  read@1.0.7:
    read: private
  readdirp@3.6.0:
    readdirp: private
  require-directory@2.1.1:
    require-directory: private
  require-in-the-middle@5.2.0:
    require-in-the-middle: private
  resolve-from@4.0.0:
    resolve-from: private
  resolve@1.22.11:
    resolve: private
  router@2.2.0:
    router: private
  run-series@1.1.9:
    run-series: private
  safe-buffer@5.2.1:
    safe-buffer: private
  safer-buffer@2.1.2:
    safer-buffer: private
  sax@1.4.1:
    sax: private
  semver@7.7.2:
    semver: private
  send@0.19.0:
    send: private
  serve-static@1.16.2:
    serve-static: private
  setprototypeof@1.2.0:
    setprototypeof: private
  shebang-command@2.0.0:
    shebang-command: private
  shebang-regex@3.0.0:
    shebang-regex: private
  shimmer@1.2.1:
    shimmer: private
  side-channel-list@1.0.0:
    side-channel-list: private
  side-channel-map@1.0.1:
    side-channel-map: private
  side-channel-weakmap@1.0.2:
    side-channel-weakmap: private
  side-channel@1.1.0:
    side-channel: private
  signal-exit@3.0.7:
    signal-exit: private
  smart-buffer@4.2.0:
    smart-buffer: private
  socks-proxy-agent@8.0.5:
    socks-proxy-agent: private
  socks@2.8.7:
    socks: private
  source-map-support@0.5.21:
    source-map-support: private
  source-map@0.6.1:
    source-map: private
  sprintf-js@1.1.2:
    sprintf-js: private
  statuses@2.0.1:
    statuses: private
  streamx@2.23.0:
    streamx: private
  string-width@4.2.3:
    string-width: private
  strip-ansi@6.0.1:
    strip-ansi: private
  supports-color@7.2.0:
    supports-color: private
  supports-preserve-symlinks-flag@1.0.0:
    supports-preserve-symlinks-flag: private
  systeminformation@5.27.11:
    systeminformation: private
  tar-fs@3.0.4:
    tar-fs: private
  tar-stream@3.1.7:
    tar-stream: private
  text-decoder@1.2.3:
    text-decoder: private
  through@2.3.8:
    through: private
  to-regex-range@5.0.1:
    to-regex-range: private
  toidentifier@1.0.1:
    toidentifier: private
  tr46@0.0.3:
    tr46: private
  tslib@1.9.3:
    tslib: private
  tslib@2.8.1:
    tslib: private
  tv4@1.3.0:
    tv4: private
  tx2@1.0.5:
    tx2: private
  type-is@1.6.18:
    type-is: private
  unbzip2-stream@1.4.3:
    unbzip2-stream: private
  undici-types@7.16.0:
    undici-types: private
  unpipe@1.0.0:
    unpipe: private
  uri-js@4.4.1:
    uri-js: private
  url-template@2.0.8:
    url-template: private
  urlpattern-polyfill@10.0.0:
    urlpattern-polyfill: private
  utils-merge@1.0.1:
    utils-merge: private
  uuid@9.0.1:
    uuid: private
  vary@1.1.2:
    vary: private
  vizion@2.2.1:
    vizion: private
  webidl-conversions@3.0.1:
    webidl-conversions: private
  whatwg-url@5.0.0:
    whatwg-url: private
  which@2.0.2:
    which: private
  wrap-ansi@7.0.0:
    wrap-ansi: private
  wrappy@1.0.2:
    wrappy: private
  y18n@5.0.8:
    y18n: private
  yallist@4.0.0:
    yallist: private
  yargs-parser@21.1.1:
    yargs-parser: private
  yargs@17.7.2:
    yargs: private
  yauzl@2.10.0:
    yauzl: private
  zod-to-json-schema@3.24.6(zod@3.25.76):
    zod-to-json-schema: private
  zod@3.25.76:
    zod: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@10.18.3
pendingBuilds: []
prunedAt: Mon, 20 Oct 2025 23:42:00 GMT
publicHoistPattern: []
registries:
  '@jsr': https://npm.jsr.io/
  default: https://registry.npmjs.org/
skipped: []
storeDir: /Users/lorenzorasmussen/.local/share/pnpm/store/v10
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 120
